modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"
issueTrackerURL="https://github.com/salvadormg15/Rubber-Duck/issues"

[[mods]]
    modId="rubber_duck"
    version="2.0.0-beta"
    displayName="Rubber Duck"
    updateJSONURL="https://gist.githubusercontent.com/salvadormg15/f73e087096fbc1718d101c6d61389352/raw/"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/rubber-duck"
    logoFile="rubber_duck.png"
    authors="Salvadormg15"
    description="We just need a Rubber Duck to be happy"

[[dependencies.rubber_duck]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.rubber_duck]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.rubber_duck]]
    modId="curios"
    mandatory=true
    versionRange="[1.18.2-5.0.7.1,)"
    ordering="NONE"
    side="BOTH"